new from workdir

diff --git a/scripts/build_openh264 b/scripts/build_openh264
--- a/scripts/build_openh264
+++ b/scripts/build_openh264
@@ -7,28 +7,88 @@
 # # # # # # # # # # # # # # #  OPENH264  # # # # # # # # # # # # # # # # # # #
 OPENH264_DOWNLOAD_URL="https://github.com/cisco/openh264/archive/v$OPENH264_VERSION.tar.gz"
 
-set_android_paths
 
-## debug
-echo -e "\n$R PATH=$PATH$E\n"
+## Cleans openh264 stuf
+function clean_openh()
+{
+    echoy "Cleaning openh264 stuff"
+    if [ -d "$ROOT_LIB_DIR/$OPENH264_DIR_NAME" ]; then
+        rm -rf "$ROOT_LIB_DIR/$OPENH264_DIR_NAME"
+    fi
+    if [ -d "/tmp/$OPENH264_DIR_NAME" ]; then
+        rm -rf "/tmp/$OPENH264_DIR_NAME"
+    fi
+    if [ -f "/tmp/openh264.tar.gz" ]; then
+        rm "/tmp/openh264.tar.gz"
+    fi
+    if [ -d /tmp/wels ]; then
+        rm -rf /tmp/wels
+    fi
+    echog "done"
+}
 
-OPENH264_PATH="$DOWNLOAD_DIR/$OPENH264_DIR_NAME"
+## Download needed source
+function download_oh()
+{
+    echoy "Downloading OpenH264 V${OPENH264_VERSION} ..."
+    cd /tmp
+    curl -L -# -o openh264.tar.gz "$OPENH264_DOWNLOAD_URL" 2>&1
+    check_return $?
+}
 
-mkdir -p tmp
-ln -sf $ANDROID_NDK_HOME/prebuilt/$HOST_TAG/bin/yasm tmp/nasm
-export PATH=$(pwd)/tmp:$PATH
+## Build for arch
+function do_build()
+{
+    cd "/tmp/$OPENH264_DIR_NAME"
 
-LIB_PATH="${OPENH264_BUILD_OUT_PATH}/libs"
-LOG_PATH="${OPENH264_BUILD_OUT_PATH}/logs"
+    TOOLCHAIN=""
+    REAL_ARCH=""
+    if [ "$1" == "arm64-v8a" ]; then
+        TOOLCHAIN="aarch64-linux-android-clang"
+        REAL_ARCH="arm64"
+        export PATH="$ANDROID_DIR/android-ndk-$ANDROID_NDK_VERSION/sysroot/usr/include/aarch64-linux-android:$PATH"
+    else
+        TOOLCHAIN="arm-linux-androideabi-clang"
+        REAL_ARCH="arm"
+        export PATH="$ANDROID_DIR/android-ndk-$ANDROID_NDK_VERSION/sysroot/usr/include/arm-linux-androideabi:$PATH"
+    fi
 
-echo -e "$Y \nDownloading OpenH264 V${OPENH264_VERSION} ...$E\n"
-cd "$DOWNLOAD_DIR"
+    echoy "Cleaning..."
+    make clean OS=android NDKROOT=$ANDROID_NDK_HOME ANDROID_API=$ANDROID_TARGET_API TARGET=android-$ANDROID_TARGET_API ARCH=$REAL_ARCH NDK_TOOLCHAIN="$TOOLCHAIN" 2>&1 >/dev/null
+    echoy "Compiling oh264..."
+    make OS=android NDKROOT=$ANDROID_NDK_HOME ANDROID_API=$ANDROID_TARGET_API TARGET=android-$ANDROID_TARGET_API ARCH=$REAL_ARCH NDK_TOOLCHAIN="$TOOLCHAIN"
+    check_return $?
+}
 
-curl -L -# -o openh264.tar.gz "$OPENH264_DOWNLOAD_URL" 2>&1
-rm -rf "${OPENH264_DIR_NAME}"
+## Build openh264
+function build_oh()
+{
+    for arch in "${TARGET_ARCHS[@]}"
+    do
+        echoy "Extracting..."
+        cd /tmp
+        if [ -d "/tmp/$OPENH264_DIR_NAME" ]; then
+            # Clean up
+            rm -rf "/tmp/$OPENH264_DIR_NAME"
+        fi
+        tar xzf openh264.tar.gz
+        check_return $?
+        # set dependencies
+        mkdir -p wels
+        ln -sf "$ANDROID_NDK_HOME/prebuilt/$HOST_TAG/bin/yasm" /tmp/wels/nasm
+        export PATH="/tmp/wels:$PATH"
 
-echo -e "$Y OpenH264 downloaded, now extracting...\n$E"
-tar xzf openh264.tar.gz && rm openh264.tar.gz
-cd "${OPENH264_DIR_NAME}"
-make OS=android NDKROOT=$ANDROID_NDK_HOME TARGET=android-29 ARCH=$OPENH264_ARCH NDK_TOOLCHAIN_VERSION=clang
+        do_build "$arch"
+    done
+}
+
 # # # # # S T A R T # # #
+echoy "\nCompiling Openh264\n"
+set_android_paths
+#clean_openh
+#download_oh
+build_oh
+clean_openh
+
+# make OS=android NDKROOT=/home/bin/android/android-ndk-r21d TARGET=android-29 ARCH=arm NDK_TOOLCHAIN=arm-linux-androideabi-clang
+# make OS=android NDKROOT=/home/bin/android/android-ndk-r21d TARGET=android-29 NDKLEVEL=16 ARCH=arm NDK_TOOLCHAIN_VERSION=clang libraries
diff --git a/scripts/config b/scripts/config
--- a/scripts/config
+++ b/scripts/config
@@ -11,7 +11,6 @@ G="\033[92m"  # Green color
 
 
 # The git repository shall be saved in this directory
-#WORKING_ROOT_DIR="/Users/buri/Projects/work"
 WORKING_ROOT_DIR="/home/bin"
 
 # The output of the final result
@@ -20,7 +19,7 @@ OUTPUT_DIR="$WORKING_ROOT_DIR/out"
 # Directory where libraries, as openh264 are saved
 ROOT_LIB_DIR="$WORKING_ROOT_DIR/libs"
 
-# Can be: darwin-x86_64, windows-x86_64,linux-x86_64 if you are on those hosts
+# Can be: darwin-x86_64, windows-x86_64, linux-x86_64 if you are on those hosts
 HOST_TAG="linux-x86_64"
 
 # Target architectures that you want to build
@@ -95,6 +94,7 @@ function echog()
 function set_android_paths()
 {
     echog "Setting paths:"
+    export NDK_TOOLCHAIN=clang
     export NDK_TOOLCHAIN_VERSION=clang
     export PATH="$NDK_TOOLCHAIN_VERSION:$PATH"
     export ANDROID_NDK_HOME="$ANDROID_DIR/android-ndk-$ANDROID_NDK_VERSION"
@@ -112,4 +112,20 @@ function set_android_paths()
     echoy "$(env | grep ANDROID_NDK_HOME)"
     echoy "$(env | grep ANDROID_SDK_HOME)"
     echoy "$(env | grep TOOLCHAIN_PATH)"
+}
+
+ ## Checks the return value of the last command and exits in case of failure
+function check_return()
+{
+    if [ $@ = 0 ]; then
+        echor "No arguments for check_return!"
+        return
+    fi
+    RETVAL=$1   
+    if [ $RETVAL -ne 0 ]; then
+        echor "ERROR: Function returned $RETVAL, exiting with failure"
+        echoy "Check logs in $BUILD_LOGS_PATH"
+        exit $RETVAL
+    fi
+    echog "    ...done"
 }
